apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: servicio-openai-assistant
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/project-ai-engineering/repo-openai-assistant/image-v4-openai-assistant:latest
          env:
          ports:
            - containerPort: 4000